[package]
name = "discord-message-source"
version = "1.0.0"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2018"

[dependencies]
#bot
serenity = "0.10.9"

# logging
env_logger = "0.9.0"
pretty_env_logger = "0.4.0"
log = "0.4.14"

# asynchronous
tokio = { version = "1.3", features = ["macros", "rt-multi-thread","signal"] }
reqwest = { version = "0.11",default-features = false,features = ["rustls","socks"] }
smol = "1.2.5"

# tools
url = "2.2.2"
once_cell = "1.8.0"
dashmap = { version = "4.0" , features = ["serde"] }
educe = "0.4.18"

# error handling
thiserror = "1.0"
anyhow = "1.0"

# encoding and decoding
base64-url = "1.4.8"

# serialization
serde = { version = "1.0", features = ["derive","rc"] }
serde_json = "1.0"
serde_yaml = "0.8"

# mesagisto
nats = "0.15.2"
mesagisto-client = { git = "https://github.com/MeowCat-Studio/mesagisto-client-rs.git" }
automatic-config = { git = "https://github.com/Itsusinn/automatic-config-rs.git" }
singleton = { git = "https://github.com/Itsusinn/singleton-rs.git", rev = "bee321c" }
