[package]
name = "discord-message-source"
version = "1.3.0-rc"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2021"

[dependencies]
#bot
serenity = { version = "0.11.1", features = ["gateway"] }

# logging
tracing="0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter","tracing-log"]}
log="0.4.14"

# asynchronous
tokio = { version = "1.17.0",default-features = false,features = ["macros", "rt-multi-thread","signal"] }
reqwest = { version = "0.11.10",default-features = false,features = ["rustls","rustls-tls-webpki-roots","rustls-tls-native-roots"] }
smol = "1.2.5"
sled = "0.34.7"

# tools
url = "2.2.2"
once_cell = "1.10.0"
dashmap = { version = "5.0.0" , features = ["serde"] }
educe = {version = "0.4.18", default-features = false,features = ["Default"]}
arcstr = { version = "1.1.3", features = ["serde"] }
either = "1.6.1"
infer = "0.7.0"
yaml-rust = "0.4.5"
linked-hash-map = "0.5.4"

# error handling
thiserror = "1.0.30"
anyhow = "1.0.53"

# encoding and decoding
base64-url = "1.4.10"

# serialization
serde = { version = "1.0.136", features = ["derive","rc"] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
serde_cbor = "0.11.2"

# mesagisto
nats = "0.19.0"
mesagisto-client = { rev = "33bc09c", git = "https://github.com/MeowCat-Studio/mesagisto-client-rs.git"}
# mesagisto-client = { path = "../../mesagisto-client/rust" }
automatic-config = { rev = "ac1cd3ac1a225e8b7f1c80d55fe7e5ee34fad81d", git = "https://github.com/Itsusinn/automatic-config-rs.git" }
#automatic-config = { path = "/code/automatic-config-rs" }
singleton = { git = "https://github.com/Itsusinn/singleton-rs.git", rev = "bee321c" }
# singleton = { path = "/code/singleton-rs" }

[profile.release]
lto = true
codegen-units = 1
