[target.'cfg(all(target_arch = "x86"))']
rustflags = ["-C","target-cpu=sandybridge","-C","target-feature=+aes,+sse2,+sse4.1,+ssse3"]
[target.'cfg(all(target_arch = "x86_64"))']
rustflags = ["-C","target-cpu=sandybridge","-C","target-feature=+aes,+sse2,+sse4.1,+ssse3"]